//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNMSDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockDetail
    {
        public long BlockId { get; set; }
        public long ProjectId { get; set; }
        public string BlockName { get; set; }
        public Nullable<int> LoweRoof { get; set; }
        public Nullable<int> UpperRoof { get; set; }
        public Nullable<int> BlockQty { get; set; }
    
        public virtual ProjectMaster ProjectMaster { get; set; }
    }
}
