//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNMSDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoqEntryDetail
    {
        public long BOQId { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public Nullable<long> DescriptionId { get; set; }
        public string DescriptionName { get; set; }
        public Nullable<long> MainItemId { get; set; }
        public string MainItem { get; set; }
        public string SubItem { get; set; }
        public string SubSubItem { get; set; }
        public string BoqRef { get; set; }
        public string Task { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> UnitRate { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> WorkdonePer { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<long> Priority { get; set; }
        public string RefId { get; set; }
        public string TaskId { get; set; }
        public string ParentId { get; set; }
        public Nullable<long> ClientId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> Workdonedate { get; set; }
        public string BOQType { get; set; }
        public string BOQRefId { get; set; }
        public Nullable<decimal> Workdonecost { get; set; }
        public string Flag { get; set; }
        public string dep { get; set; }
        public string Predec { get; set; }
        public string Criticaltaskid { get; set; }
        public Nullable<System.DateTime> RVStartDate { get; set; }
        public Nullable<System.DateTime> RVEndDate { get; set; }
        public Nullable<decimal> RDuration { get; set; }
    }
}
