//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNMSDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoqReviseDetail
    {
        public long ReviseId { get; set; }
        public long BOQId { get; set; }
        public string ReviseType { get; set; }
        public Nullable<System.DateTime> RStartDate { get; set; }
        public Nullable<System.DateTime> REndDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Flag { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public Nullable<long> ProjectId { get; set; }
    }
}
