//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNMSDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriticalPathDetail
    {
        public long CriticalId { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public Nullable<long> BOQId { get; set; }
        public string TaskId { get; set; }
        public string BOQRefId { get; set; }
        public string dep { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<decimal> ES { get; set; }
        public Nullable<decimal> EF { get; set; }
        public string Predec { get; set; }
        public Nullable<decimal> LS { get; set; }
        public Nullable<decimal> LF { get; set; }
        public Nullable<decimal> Slack { get; set; }
        public string Criticaltaskid { get; set; }
        public string Flag { get; set; }
    }
}
