//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNMSDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatabaseDetail
    {
        public long DatabaseId { get; set; }
        public int CompanyId { get; set; }
        public long ClientId { get; set; }
        public string Server_Name { get; set; }
        public string DB_Name { get; set; }
        public string DB_Username { get; set; }
        public string DB_Password { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Company Company { get; set; }
    }
}
