//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNMSDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainItemMaster
    {
        public long MainItemId { get; set; }
        public long ProjectId { get; set; }
        public string MainItemName { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual ProjectMaster ProjectMaster { get; set; }
    }
}
