//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNMSDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDescription
    {
        public long PDId { get; set; }
        public long ProjectId { get; set; }
        public Nullable<int> Foundation { get; set; }
        public Nullable<int> Basement { get; set; }
        public Nullable<int> Podium { get; set; }
        public Nullable<int> Mezanine { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual ProjectMaster ProjectMaster { get; set; }
    }
}
