//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNMSDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public long UserId { get; set; }
        public int CompanyId { get; set; }
        public Nullable<long> ClientId { get; set; }
        public string ClientCode { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int User_Role_Id { get; set; }
        public Nullable<System.DateTime> MaintanceDate { get; set; }
        public Nullable<System.DateTime> ExprieDate { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Modified_by { get; set; }
        public Nullable<System.DateTime> Modfied_Date { get; set; }
        public Nullable<int> Status { get; set; }
        public string Loginuser { get; set; }
        public string Designation { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<long> SupplierId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Company Company { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
