//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNMSDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserValidity
    {
        public long ValidityId { get; set; }
        public long UserId { get; set; }
        public long ClientId { get; set; }
        public Nullable<System.DateTime> MaintanceDate { get; set; }
        public Nullable<System.DateTime> ExprieDate { get; set; }
    }
}
