//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNMSDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariationMaster
    {
        public long VID { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public Nullable<long> ClientId { get; set; }
        public string VariationName { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
